workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    environment:
      node: 22.2.0
      xcode: latest
      cocoapods: default
      vars:
        APP_ID: "com.yourcompany.listo"

    scripts:
      - npm install
      - npm run build                       # Generates `build/` directory for Capacitor
      - npx cap sync ios
      - |
          cd ios
          pod install
          cd ..
      - xcodebuild -workspace ios/App.xcworkspace -scheme App -sdk iphoneos -configuration Release

    artifacts:
      - ios/build/**/Build/Products/Release-iphoneos/*.ipa
