workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini
    environment:
      node: 18
      xcode: latest
      cocoapods: default
      vars:
        APP_ID: "com.yourcompany.listo"
    scripts:
      - npm install
      - npx cap sync ios
      - cd ios
      - pod install
      - cd ..
      - xcode-project build -w ios/App.xcworkspace -s App -sdk iphoneos -configuration Release
    artifacts:
      - ios/build/**/Build/Products/Release-iphoneos/*.ipa
